datasource:
  filepath: /Users/xiaoche/king/xxx/datasource/datasource-sspku-application.properties

server:
  port: 8080  #访问项目端口
  context-path: /  #访问项目名称
spring:
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**


