datasource:
  filepath: /Users/xiaoche/king/luckincoffee/datasource/datasource-sspku-application.properties

server:
  port: 8080  #访问项目端口
  context-path: /  #访问项目名称
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.miniapp: DEBUG

spring:
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**





